-- Review and back up PostgreSQL before running this migration.
-- Execute in a maintenance window; do not run concurrently with application writes.
BEGIN;

CREATE TABLE IF NOT EXISTS scientific_records (
    resource_id varchar(255) PRIMARY KEY,
    revision bigint NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL DEFAULT 'DRAFT',
    version_label varchar(40),
    version_doi varchar(255),
    conceptual_doi varchar(255),
    previous_resource_id varchar(255),
    license_id varchar(100),
    access_level varchar(30) DEFAULT 'OPEN',
    embargo_until timestamptz,
    language varchar(16),
    discipline varchar(255),
    keywords varchar(2000),
    orcid varchar(255),
    institution varchar(255),
    ror varchar(255),
    related_publications varchar(2000),
    methodology varchar(2000),
    submitted_at timestamptz,
    published_at timestamptz,
    withdrawn_at timestamptz,
    withdrawal_reason varchar(1000)
);

-- Safe when the table was created by an earlier revision of this branch.
ALTER TABLE scientific_records ADD COLUMN IF NOT EXISTS embargo_until timestamptz;

CREATE TABLE IF NOT EXISTS scientific_record_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id varchar(255) NOT NULL,
    actor varchar(100) NOT NULL,
    action varchar(40) NOT NULL,
    created_at timestamptz NOT NULL,
    detail varchar(1000)
);
CREATE INDEX IF NOT EXISTS idx_scientific_record_events_resource ON scientific_record_events(resource_id, created_at);

CREATE TABLE IF NOT EXISTS file_fixity_states (
    content_id bigint PRIMARY KEY,
    expected_sha256 varchar(64),
    actual_sha256 varchar(64),
    status varchar(24) NOT NULL,
    checked_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS file_provenance_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id varchar(255) NOT NULL,
    content_id bigint,
    relative_path varchar(1024) NOT NULL,
    action varchar(24) NOT NULL,
    actor varchar(100) NOT NULL,
    sha256 varchar(64),
    occurred_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_file_provenance_resource
    ON file_provenance_events(resource_id, occurred_at, id);

CREATE TABLE IF NOT EXISTS fixity_audit_runs (
    id varchar(36) PRIMARY KEY,
    status varchar(16) NOT NULL,
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    checked bigint NOT NULL DEFAULT 0,
    matched bigint NOT NULL DEFAULT 0,
    mismatched bigint NOT NULL DEFAULT 0,
    missing bigint NOT NULL DEFAULT 0,
    no_baseline bigint NOT NULL DEFAULT 0,
    unsupported bigint NOT NULL DEFAULT 0,
    errors bigint NOT NULL DEFAULT 0,
    message varchar(500)
);
CREATE INDEX IF NOT EXISTS idx_fixity_audit_runs_started ON fixity_audit_runs(started_at DESC);

CREATE TABLE IF NOT EXISTS scientific_relations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id varchar(255) NOT NULL,
    kind varchar(20) NOT NULL,
    identifier_type varchar(12) NOT NULL,
    relation_type varchar(32) NOT NULL,
    identifier varchar(500) NOT NULL,
    title varchar(255)
);
CREATE INDEX IF NOT EXISTS idx_scientific_relations_resource ON scientific_relations(resource_id);

-- Scientific identity is per creator, not a single ORCID shared by the dataset.
CREATE TABLE IF NOT EXISTS scientific_creators (
    id BIGSERIAL PRIMARY KEY,
    resource_id VARCHAR(255) NOT NULL,
    creator_id BIGINT NOT NULL,
    orcid VARCHAR(255),
    institution VARCHAR(255),
    ror VARCHAR(255),
    CONSTRAINT uq_scientific_creator UNIQUE (resource_id, creator_id)
);
CREATE INDEX IF NOT EXISTS idx_scientific_creators_resource ON scientific_creators(resource_id);
ALTER TABLE scientific_creators ADD COLUMN IF NOT EXISTS orcid_authenticated_at timestamptz;
ALTER TABLE scientific_creators ADD COLUMN IF NOT EXISTS orcid_authenticated_by varchar(80);

-- OAuth authorization requests are short-lived and consumed atomically by a row lock.
CREATE TABLE IF NOT EXISTS orcid_oauth_states (
    state_hash char(64) PRIMARY KEY,
    resource_id varchar(255) NOT NULL,
    creator_id bigint NOT NULL,
    username varchar(80) NOT NULL,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_orcid_oauth_expires ON orcid_oauth_states(expires_at);

-- Extra institutions per author; scientific_creators.institution/ror remains
-- the first-affiliation fallback for existing records, so no lossy backfill is needed.
CREATE TABLE IF NOT EXISTS scientific_affiliations (
    id BIGSERIAL PRIMARY KEY,
    resource_id VARCHAR(255) NOT NULL,
    creator_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL,
    institution VARCHAR(255) NOT NULL,
    ror VARCHAR(255),
    CONSTRAINT uq_scientific_affiliation_order UNIQUE (resource_id, creator_id, sort_order)
);
CREATE INDEX IF NOT EXISTS idx_scientific_affiliations_resource ON scientific_affiliations(resource_id);

-- Funder and award/project references are per released version and map to DataCite fundingReferences.
CREATE TABLE IF NOT EXISTS scientific_funding (
    id BIGSERIAL PRIMARY KEY,
    resource_id VARCHAR(255) NOT NULL,
    funder_name VARCHAR(255) NOT NULL,
    funder_ror VARCHAR(255),
    award_number VARCHAR(100),
    award_title VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_scientific_funding_resource ON scientific_funding(resource_id);

-- Shared authentication rate limits; bucket_key is an HMAC, not an email or IP.
CREATE TABLE IF NOT EXISTS auth_rate_windows (
    bucket_key VARCHAR(64) PRIMARY KEY,
    expires_at TIMESTAMPTZ NOT NULL,
    attempts INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_auth_rate_windows_expires ON auth_rate_windows(expires_at);

-- Short-lived, curator-issued read-only access for an external reviewer.
-- The plaintext bearer token must never be stored in this table.
CREATE TABLE IF NOT EXISTS reviewer_access_links (
    id BIGSERIAL PRIMARY KEY,
    resource_id VARCHAR(255) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_reviewer_access_resource ON reviewer_access_links(resource_id);

CREATE TABLE IF NOT EXISTS doi_registrations (
    registration_key varchar(260) PRIMARY KEY,
    revision bigint NOT NULL DEFAULT 0,
    resource_id varchar(255) NOT NULL,
    kind varchar(12) NOT NULL,
    doi varchar(255) NOT NULL UNIQUE,
    api_host varchar(128) NOT NULL,
    state varchar(20) NOT NULL,
    last_synced_at timestamptz,
    last_error varchar(500)
);
CREATE INDEX IF NOT EXISTS idx_doi_registrations_resource ON doi_registrations(resource_id);

CREATE TABLE IF NOT EXISTS doi_sync_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_key varchar(260) NOT NULL,
    action varchar(32) NOT NULL,
    result varchar(20) NOT NULL,
    occurred_at timestamptz NOT NULL,
    detail varchar(500)
);
CREATE INDEX IF NOT EXISTS idx_doi_sync_events_key ON doi_sync_events(registration_key, occurred_at);

ALTER TABLE repo_users ADD COLUMN IF NOT EXISTS password_changed_at timestamptz;

CREATE INDEX IF NOT EXISTS idx_scientific_records_status ON scientific_records(status);
CREATE INDEX IF NOT EXISTS idx_scientific_records_previous ON scientific_records(previous_resource_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_scientific_records_version_doi
    ON scientific_records(lower(version_doi)) WHERE version_doi IS NOT NULL;


CREATE TABLE IF NOT EXISTS scientific_collections (
    id varchar(36) PRIMARY KEY,
    revision bigint NOT NULL DEFAULT 0,
    title varchar(200) NOT NULL,
    description varchar(2000),
    kind varchar(20) NOT NULL,
    published boolean NOT NULL DEFAULT false
);
CREATE TABLE IF NOT EXISTS scientific_collection_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id varchar(36) NOT NULL,
    resource_id varchar(255) NOT NULL,
    CONSTRAINT uq_collection_resource UNIQUE(collection_id, resource_id),
    CONSTRAINT fk_collection_member FOREIGN KEY(collection_id) REFERENCES scientific_collections(id)
);
CREATE INDEX IF NOT EXISTS idx_collection_members_collection ON scientific_collection_members(collection_id);

ALTER TABLE scientific_records ADD COLUMN IF NOT EXISTS summary varchar(5000);
ALTER TABLE scientific_records ADD COLUMN IF NOT EXISTS temporal_start date;
ALTER TABLE scientific_records ADD COLUMN IF NOT EXISTS temporal_end date;
ALTER TABLE scientific_records ADD COLUMN IF NOT EXISTS geographic_coverage varchar(1000);
CREATE TABLE IF NOT EXISTS scientific_record_translations (
    resource_id varchar(255) NOT NULL REFERENCES scientific_records(resource_id),
    language varchar(35) NOT NULL,
    localized_title varchar(500),
    localized_summary varchar(5000),
    PRIMARY KEY(resource_id,language)
);

CREATE TABLE IF NOT EXISTS scientific_privacy_assessments (
    resource_id varchar(255) PRIMARY KEY,
    revision bigint NOT NULL DEFAULT 0,
    classification varchar(20) NOT NULL,
    assessment_note varchar(2000),
    review_state varchar(20) NOT NULL,
    updated_at timestamptz,
    reviewed_at timestamptz,
    reviewed_by varchar(80),
    review_note varchar(1000)
);

COMMIT;

-- Author-declared scientific provenance; separate from machine-observed file events.
ALTER TABLE scientific_records ADD COLUMN IF NOT EXISTS production_description VARCHAR(5000);
ALTER TABLE scientific_records ADD COLUMN IF NOT EXISTS processing_description VARCHAR(5000);
ALTER TABLE scientific_records ADD COLUMN IF NOT EXISTS processing_tools VARCHAR(2000);

-- Vocabulary governance: a pending proposal never replaces the approved list.
CREATE TABLE IF NOT EXISTS scientific_vocabulary_registry (
 kind varchar(20) PRIMARY KEY, revision bigint NOT NULL DEFAULT 0,
 approved boolean NOT NULL DEFAULT false,
 proposal_note varchar(1000), proposed_by varchar(80), approved_by varchar(80),
 proposed_at timestamp(6) with time zone, approved_at timestamp(6) with time zone
);
CREATE TABLE IF NOT EXISTS scientific_vocabulary_approved (
 kind varchar(20) NOT NULL REFERENCES scientific_vocabulary_registry(kind),
 position integer NOT NULL, value varchar(255) NOT NULL, PRIMARY KEY(kind,position)
);
CREATE TABLE IF NOT EXISTS scientific_vocabulary_proposed (
 kind varchar(20) NOT NULL REFERENCES scientific_vocabulary_registry(kind),
 position integer NOT NULL, value varchar(255) NOT NULL, PRIMARY KEY(kind,position)
);

-- Approved metadata profiles and frozen per-dataset rule snapshots.
CREATE TABLE IF NOT EXISTS scientific_metadata_profiles (
 id varchar(50) PRIMARY KEY, revision bigint NOT NULL DEFAULT 0, approved_revision bigint,
 active boolean NOT NULL DEFAULT false,
 approved_name varchar(100), approved_description varchar(1000), approved_license_id varchar(100), approved_language varchar(16), approved_discipline varchar(255),
 proposed_name varchar(100), proposed_description varchar(1000), proposed_license_id varchar(100), proposed_language varchar(16), proposed_discipline varchar(255),
 proposal_note varchar(1000), proposed_by varchar(80), approved_by varchar(80), updated_by varchar(80),
 proposed_at timestamp(6) with time zone, approved_at timestamp(6) with time zone, updated_at timestamp(6) with time zone
);
CREATE TABLE IF NOT EXISTS scientific_profile_approved_fields (
 profile_id varchar(50) NOT NULL REFERENCES scientific_metadata_profiles(id), field_name varchar(80) NOT NULL, PRIMARY KEY(profile_id,field_name)
);
CREATE TABLE IF NOT EXISTS scientific_profile_proposed_fields (
 profile_id varchar(50) NOT NULL REFERENCES scientific_metadata_profiles(id), field_name varchar(80) NOT NULL, PRIMARY KEY(profile_id,field_name)
);
ALTER TABLE scientific_records ADD COLUMN IF NOT EXISTS metadata_profile_id varchar(50);
ALTER TABLE scientific_records ADD COLUMN IF NOT EXISTS metadata_profile_name varchar(100);
ALTER TABLE scientific_records ADD COLUMN IF NOT EXISTS metadata_profile_revision bigint;
CREATE TABLE IF NOT EXISTS scientific_record_profile_fields (
 resource_id varchar(255) NOT NULL REFERENCES scientific_records(resource_id), field_name varchar(80) NOT NULL, PRIMARY KEY(resource_id,field_name)
);

-- Durable search indexing: safe to rerun, no deletion of existing data.
CREATE TABLE IF NOT EXISTS search_index_tasks (
    id varchar(36) PRIMARY KEY,
    resource_id varchar(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS search_index_tasks_created_idx ON search_index_tasks(created_at);
ALTER TABLE scientific_records ADD COLUMN IF NOT EXISTS doi_publication_pending boolean NOT NULL DEFAULT false;
ALTER TABLE scientific_records ADD COLUMN IF NOT EXISTS doi_publication_owner varchar(255);
ALTER TABLE scientific_records ADD COLUMN IF NOT EXISTS doi_publication_running boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS usage_observations (
 id varchar(64) PRIMARY KEY, resource_id varchar(255) NOT NULL, kind varchar(16) NOT NULL,
 usage_day date NOT NULL, last_seen_at timestamp(6) with time zone NOT NULL, requests bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS usage_observations_day_idx ON usage_observations(usage_day);
CREATE TABLE IF NOT EXISTS repository_self_assessments (
 requirement_id varchar(3) PRIMARY KEY, revision bigint NOT NULL DEFAULT 0, state varchar(32) NOT NULL,
 responsible varchar(255), statement varchar(5000), evidence varchar(4000), updated_by varchar(80) NOT NULL,
 updated_at timestamp(6) with time zone NOT NULL
);
