-- Review and back up PostgreSQL before running this migration.
-- Execute in a maintenance window; do not run concurrently with application writes.
BEGIN;

CREATE TABLE IF NOT EXISTS scientific_records (
    resource_id varchar(255) PRIMARY KEY,
    revision bigint NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL DEFAULT 'DRAFT',
    version_label varchar(40),
    version_doi varchar(255),
    conceptual_doi varchar(255),
    previous_resource_id varchar(255),
    license_id varchar(100),
    access_level varchar(30) DEFAULT 'OPEN',
    embargo_until timestamptz,
    language varchar(16),
    discipline varchar(255),
    keywords varchar(2000),
    orcid varchar(255),
    institution varchar(255),
    ror varchar(255),
    related_publications varchar(2000),
    methodology varchar(2000),
    submitted_at timestamptz,
    published_at timestamptz,
    withdrawn_at timestamptz,
    withdrawal_reason varchar(1000)
);

-- Safe when the table was created by an earlier revision of this branch.
ALTER TABLE scientific_records ADD COLUMN IF NOT EXISTS embargo_until timestamptz;

CREATE TABLE IF NOT EXISTS scientific_record_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id varchar(255) NOT NULL,
    actor varchar(100) NOT NULL,
    action varchar(40) NOT NULL,
    created_at timestamptz NOT NULL,
    detail varchar(1000)
);
CREATE INDEX IF NOT EXISTS idx_scientific_record_events_resource ON scientific_record_events(resource_id, created_at);

CREATE TABLE IF NOT EXISTS file_fixity_states (
    content_id bigint PRIMARY KEY,
    expected_sha256 varchar(64),
    actual_sha256 varchar(64),
    status varchar(24) NOT NULL,
    checked_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS doi_registrations (
    registration_key varchar(260) PRIMARY KEY,
    revision bigint NOT NULL DEFAULT 0,
    resource_id varchar(255) NOT NULL,
    kind varchar(12) NOT NULL,
    doi varchar(255) NOT NULL UNIQUE,
    api_host varchar(128) NOT NULL,
    state varchar(20) NOT NULL,
    last_synced_at timestamptz,
    last_error varchar(500)
);
CREATE INDEX IF NOT EXISTS idx_doi_registrations_resource ON doi_registrations(resource_id);

CREATE TABLE IF NOT EXISTS doi_sync_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_key varchar(260) NOT NULL,
    action varchar(32) NOT NULL,
    result varchar(20) NOT NULL,
    occurred_at timestamptz NOT NULL,
    detail varchar(500)
);
CREATE INDEX IF NOT EXISTS idx_doi_sync_events_key ON doi_sync_events(registration_key, occurred_at);

ALTER TABLE repo_users ADD COLUMN IF NOT EXISTS password_changed_at timestamptz;

CREATE INDEX IF NOT EXISTS idx_scientific_records_status ON scientific_records(status);
CREATE INDEX IF NOT EXISTS idx_scientific_records_previous ON scientific_records(previous_resource_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_scientific_records_version_doi
    ON scientific_records(lower(version_doi)) WHERE version_doi IS NOT NULL;

COMMIT;
