#!/usr/bin/env node
// Local UI fixtures, no live database or backend authorization assertions.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const puppeteer=require('../a11y/node_modules/puppeteer-core'),axe=require('../a11y/node_modules/axe-core');
const root=path.resolve(__dirname,'../../src/main/resources/static');let requests=0;
const server=http.createServer((req,res)=>{
 if(req.url.startsWith('/api/')){requests++;res.setHeader('Content-Type','application/json');
  if(req.url.startsWith('/api/v1/my-deposit-tasks'))res.end(JSON.stringify({items:[{resourceId:'fixture',title:'Título de autor <original>',status:'DRAFT',completionPercent:40,blockers:['required'],pending:[{code:'methodology',label:'Metodología',required:true},{code:'profile:processingTools',label:'Perfil: Herramientas y versiones',required:true}],nextAction:'Completar metadatos y documentación'}],page:0,pages:1,total:1}));
  else res.end(JSON.stringify([{id:'fixture',titles:[{value:'Título de autor <original>'}],resourceType:{value:'DATASET'},publicationYear:'2026'}]));return;
 }
 const name=req.url.split('?')[0].slice(1);if(!/^[\w.-]+$/.test(name)||!fs.existsSync(path.join(root,name))){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path.join(root,name)));
});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await puppeteer.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.evaluateOnNewDocument(()=>{localStorage.setItem('base-repo-token','fixture');localStorage.setItem('base-repo-user',JSON.stringify({username:'fixture',role:'USER'}));});await page.setViewport({width:320,height:900});await page.goto(`http://127.0.0.1:${server.address().port}/my-datasets.html`);await page.waitForSelector('#task-list h3');await page.waitForSelector('#resource-list h2');await page.type('#filter','original');const before=requests;await page.select('[data-ui-locale]','en');assert.equal(await page.$eval('h1',n=>n.textContent),'My deposits');assert.equal(await page.$eval('#resource-list h2',n=>n.textContent),'Título de autor <original>');assert.equal(await page.$eval('#filter',n=>n.value),'original');assert.match(await page.$eval('#task-list',n=>n.textContent),/Methodology/);assert.match(await page.$eval('#task-list',n=>n.textContent),/Profile: Tools and versions/);assert.match(await page.$eval('#task-status',n=>n.textContent),/1 active deposits/);await new Promise(r=>setTimeout(r,350));assert.equal(requests,before);await page.addScriptTag({content:axe.source});const report=await page.evaluate(()=>axe.run());assert.deepEqual(report.violations.map(v=>v.id),[]);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('My deposits/tasks es/en, metadata/control preservation, no extra requests, English 320px axe: PASS');
 }finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
