#!/usr/bin/env node
// Local operational UI fixtures, not a live preservation audit.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const puppeteer=require('../a11y/node_modules/puppeteer-core'),axe=require('../a11y/node_modules/axe-core');
const root=path.resolve(__dirname,'../../src/main/resources/static');let requests=0,fail=false;
const server=http.createServer((req,res)=>{
 if(req.url.startsWith('/api/')){requests++;res.setHeader('Content-Type','application/json');if(fail){res.writeHead(503);res.end(JSON.stringify({detail:'Mensaje original del servidor'}));return;}
  if(req.url.endsWith('/storage'))res.end(JSON.stringify({status:'AVAILABLE',totalBytes:1234567,usableBytes:765432,unallocatedBytes:654321,measuredAt:'2026-10-08T12:00:00Z',scope:'Raw technical scope'}));
  else if(req.url.endsWith('/metrics'))res.end(JSON.stringify({published:3,inReview:1,files:7,filesChecked:5,mismatched:1,missing:1}));
  else res.end(JSON.stringify([{status:'COMPLETED',startedAt:'2026-10-08T11:00:00Z',completedAt:null,checked:5,matched:3,mismatched:1,missing:1,noBaseline:0,unsupported:0,errors:0}]));return;
 }
 const name=req.url.split('?')[0].slice(1);if(!/^[\w.-]+$/.test(name)||!fs.existsSync(path.join(root,name))){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path.join(root,name)));
});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await puppeteer.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.evaluateOnNewDocument(()=>{localStorage.setItem('base-repo-token','fixture');localStorage.setItem('base-repo-user',JSON.stringify({username:'fixture',role:'CURATOR'}));});await page.setViewport({width:320,height:900});await page.goto(`http://127.0.0.1:${server.address().port}/operations.html`);await page.waitForFunction(()=>!document.querySelector('#export-operations').disabled);const before=requests;await page.select('[data-ui-locale]','en');assert.equal(await page.$eval('h1',n=>n.textContent),'Operational status');assert.match(await page.$eval('#storage-summary',n=>n.textContent),/Capacity: 1,234,567 bytes/);assert.match(await page.$eval('#integrity-summary',n=>n.textContent),/Missing files: 1/);assert.match(await page.$eval('#operations-audits',n=>n.textContent),/Not completed/);await new Promise(r=>setTimeout(r,350));assert.equal(requests,before);await page.addScriptTag({content:axe.source});const audit=await page.evaluate(()=>axe.run());assert.deepEqual(audit.violations.map(v=>v.id),[]);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 fail=true;await page.click('#refresh-operations');await page.waitForFunction(()=>document.querySelector('#operations-status').textContent.includes('Mensaje original'));assert.match(await page.$eval('#storage-summary',n=>n.textContent),/Data unavailable/);assert(await page.$eval('#export-operations',n=>n.disabled));await page.select('[data-ui-locale]','es');assert.match(await page.$eval('#operations-status',n=>n.textContent),/Mensaje original del servidor/);assert.match(await page.$eval('#operations-status',n=>n.textContent),/Reintente la consulta/);assert.deepEqual(errors,[]);console.log('Operations es/en snapshot, localized numbers, no extra requests, failure/no stale figures, English 320px axe: PASS');
 }finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
