#!/usr/bin/env node
// Isolated core UI fixture. Shared editors/transfers are stubbed, backend authorization is not tested.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const puppeteer=require('../a11y/node_modules/puppeteer-core');const root=path.resolve(__dirname,'../../src/main/resources/static');let calls=0, submissions=0, qualityFailure=false;
const resource={id:'original',titles:[{value:'Título <original>'}],creators:[{givenName:'Autor original'}],publicationYear:'2026',publisher:'Editorial original',resourceType:{value:'DATASET',typeGeneral:'DATASET'},state:'VOLATILE'};
const science={status:'DRAFT',versionLabel:'1.0 original',licenseId:'CC-BY-4.0',accessLevel:'OPEN',institution:'Institución original',summary:'Resumen original'};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://fixture');if(url.pathname==='/fixture-fail-quality'){qualityFailure=true;res.end('ok');return;}if(url.pathname.startsWith('/api/')){calls++;if(url.pathname.endsWith('/submit')&&req.method==='POST')submissions++;res.setHeader('Content-Type','application/json');if(qualityFailure&&url.pathname.endsWith('/quality')){res.writeHead(403);res.end(JSON.stringify({detail:'Original forbidden detail'}));return;}let body={};if(url.pathname.endsWith('/doi/config'))body={enabled:true};else if(url.pathname==='/api/v1/my-dataresources')body=[resource];else if(url.pathname.endsWith('/quality'))body={completionPercent:53,checks:[{code:'description',label:'description.md',required:true,complete:false,explanation:'Description'},{code:'files',label:'Files',required:true,complete:false,explanation:'Files'},{code:'summary',label:'Summary',required:false,complete:false,explanation:'Summary'},{code:'orcid',label:'ORCID',required:false,complete:false,explanation:'ORCID'},{code:'title',label:'Title',required:true,complete:true}],blockers:['description.md','Files']};else if(url.pathname.endsWith('/doi'))body={versionState:'DRAFT',conceptualState:'DRAFT',versionRegistration:{registeredAt:'2026-10-08T12:34:56Z',lastAttemptAt:'2026-10-08T12:34:56Z',metadataVersion:0,landingPageUrl:'https://repository.invalid/'+ 'a'.repeat(500)}};else if(url.pathname.endsWith('/history'))body=[{createdAt:'2026-10-08T12:34:56Z',action:'METADATA_UPDATED',actor:'Curador original',detail:'Nota privada original'}];else if(url.pathname.endsWith('/data/'))body=[{relativePath:'archivo <original>.csv',size:123,metadata:{sha256:'checksum-original'}}];else if(url.pathname.startsWith('/api/v1/dataresources/'))body=resource;else body=science;res.end(JSON.stringify(body));return;}const name=url.pathname.slice(1);if(!/^[\w.-]+$/.test(name)||!fs.existsSync(path.join(root,name))){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript; charset=utf-8':name.endsWith('.css')?'text/css; charset=utf-8':'text/html; charset=utf-8');let data=fs.readFileSync(path.join(root,name),'utf8');if(name==='resource.html'){data=data.replace(/<script src="(?!ui-locales\.js|ui-i18n\.js|resource\.js)[^"]+"><\/script>/g,'').replace('<script src="resource.js">',`<script>window.auth={requireLogin:()=>{},user:()=>({username:'Autor original',role:'USER'}),headers:()=>({}),logout:()=>{}};window.metadataTranslations={mount:()=>({set:()=>{},get:()=>({})})};window.toast={success:()=>{},error:()=>{},successKey:()=>{},errorKey:()=>{},errorObject:()=>{}};window.transfers={download:async()=>({savedToDisk:false})};</script><script src="resource.js">`);}res.end(data);});
(async()=>{let browser;try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
 browser=await puppeteer.launch({executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewport({width:1440,height:1000});await page.goto(base+'/resource.html?id=original');await page.waitForSelector('[data-readiness-code=description]');
 assert.equal(await page.$$('.readiness-group').then(xs=>xs.length),2);assert.match(await page.$eval('#quality-pending-count',n=>n.textContent),/2 requisitos/);assert.match(await page.$eval('.readiness-card',n=>n.textContent),/Subir descripción/);
 const before=calls;await page.click('[data-readiness-code=description]');assert(await page.$eval('#description-section',n=>n.classList.contains('readiness-highlight')));assert.equal(await page.$eval('#description-modal',n=>n.open),false);assert.equal(calls,before);assert.equal(await page.evaluate(()=>document.activeElement.dataset.openModal),'description-modal');
 await page.click('[data-readiness-code=files]');assert(await page.$eval('#files-section',n=>n.classList.contains('readiness-highlight')));assert.equal(await page.$eval('#files-modal',n=>n.open),false);assert.equal(calls,before);
 await page.select('[data-ui-locale]','en').catch(()=>page.evaluate(()=>uiI18n.change('en')));assert.match(await page.$eval('#quality-pending-count',n=>n.textContent),/2 pending requirements/);assert.equal(calls,before);
 await page.click('#refresh-quality');await page.waitForFunction(()=>!document.querySelector('#refresh-quality').disabled);assert.equal(calls,before+1);
 await page.evaluate(()=>{isOwner=false;renderQuality(lastQualityReport);});assert.equal(await page.$$('[data-readiness-code]').then(xs=>xs.length),0);await page.evaluate(()=>{isOwner=true;renderQuality(lastQualityReport);});
 await page.addScriptTag({content:require('../a11y/node_modules/axe-core').source});const result=await page.evaluate(()=>axe.run());assert.deepEqual(result.violations.map(x=>x.id),[]);
 await page.setViewport({width:320,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual((await page.evaluate(()=>axe.run())).violations.map(x=>x.id),[]);
 await page.setViewport({width:1440,height:1000});await page.evaluate(()=>uiI18n.change('es'));if(process.env.E2E_SCREENSHOT_PATH)await (await page.$('.quality-panel')).screenshot({path:process.env.E2E_SCREENSHOT_PATH});assert.equal(submissions,0);assert.deepEqual(errors,[]);console.log('Readiness PASS: guided cards, required/recommended, navigation/focus/highlight without uploads, refresh, locale no extra requests, non-owner hidden actions, 320px and axe.');
}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(error=>{console.error(error);process.exitCode=1;});
