#!/usr/bin/env node
// UI fixture only, not proof of backend administrative authorization.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const puppeteer=require('../a11y/node_modules/puppeteer-core');const root=path.resolve(__dirname,'../../src/main/resources/static');const calls=[];
const entry={kind:'LICENSE',source:'APPROVED_REGISTRY',strict:true,effectiveValues:['Licencia <original>'],proposedValues:['Término propuesto original'],proposalNote:'Motivo original',proposedAt:'2026-10-08',proposedBy:'Admin original',approvedAt:'2026-10-07',approvedBy:'Aprobador original',revision:7};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://fixture');if(url.pathname.startsWith('/api/v1/scientific/vocabularies/administration')){calls.push({method:req.method,path:url.pathname});res.setHeader('Content-Type','application/json');if(req.method!=='GET'){let body='';req.on('data',chunk=>body+=chunk);req.on('end',()=>{calls.at(-1).body=JSON.parse(body);res.end('{}');});return;}res.end(JSON.stringify([entry]));return;}const name=url.pathname.slice(1);if(!/^[\w.-]+$/.test(name)||!fs.existsSync(path.join(root,name))){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript; charset=utf-8':name.endsWith('.css')?'text/css; charset=utf-8':'text/html; charset=utf-8');res.end(fs.readFileSync(path.join(root,name)));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await puppeteer.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.evaluateOnNewDocument(()=>{localStorage.setItem('base-repo-token','fixture');localStorage.setItem('base-repo-user',JSON.stringify({username:'Admin original',role:'ADMINISTRATOR'}));});await page.goto(`http://127.0.0.1:${server.address().port}/vocabulary-admin.html`);await page.waitForSelector('#vocabulary-lists button');const count=calls.length;await page.select('[data-ui-locale]','en');assert.equal(await page.$eval('h1',node=>node.textContent),'Deposit vocabularies');assert.equal(await page.$eval('#vocabulary-lists li',node=>node.textContent),'Licencia <original>');assert.equal(calls.length,count);
 await page.click('#vocabulary-lists button');await page.$eval('[name=note]',node=>node.value+=' unchanged');await page.evaluate(()=>uiI18n.change('es'));assert.equal(await page.$eval('[name=note]',node=>node.value),'Motivo original unchanged');await page.evaluate(()=>uiI18n.change('en'));assert.equal(await page.$eval('#vocabulary-modal-title',node=>node.textContent),'Propose licenses');assert.equal(calls.length,count);await page.$eval('#vocabulary-form',form=>form.requestSubmit());await page.waitForFunction(()=>!document.querySelector('#vocabulary-modal').open);const put=calls.find(call=>call.method==='PUT');assert.deepEqual(put.body,{values:['Término propuesto original'],note:'Motivo original unchanged',revision:7});
 await page.waitForSelector('#vocabulary-lists .primary');await page.click('#vocabulary-lists .primary');const before=calls.length;await page.evaluate(()=>uiI18n.change('es'));assert.equal(await page.$eval('#vocabulary-approval-values li',node=>node.textContent),'Término propuesto original');assert.equal(calls.length,before);assert.equal(calls.filter(call=>call.method==='POST').length,0);await page.$eval('#vocabulary-approval-form',form=>form.requestSubmit());await page.waitForFunction(()=>!document.querySelector('#vocabulary-approval-modal').open);assert.deepEqual(calls.find(call=>call.method==='POST').body,{revision:7});assert.deepEqual(errors,[]);console.log('Vocabulary admin es/en, original terms, modal input preservation, explicit approval and revision payload PASS');
 }finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(error=>{console.error(error);process.exitCode=1;server.close();});
