#!/usr/bin/env node
/* UI fixtures only. Real uploads/security are covered separately by wizard-smoke. */
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const puppeteer=require('../a11y/node_modules/puppeteer-core'),axe=require('../a11y/node_modules/axe-core');
const root=path.resolve(__dirname,'../../src/main/resources/static');let requests=0,writes=0,transferRequests=0,failedProfiles=false;
const server=http.createServer((req,res)=>{
 if(req.url==='/fixture-upload'){transferRequests++;req.resume();setTimeout(()=>{res.setHeader('Content-Type','application/json');res.end('{}');},1800);return;}
 if(req.url.startsWith('/api/')){requests++;if(req.method!=='GET')writes++;res.setHeader('Content-Type','application/json');
  if(req.url.includes('metadata-profiles/fields'))res.end(JSON.stringify({processingTools:'Herramientas y versiones'}));
  else if(req.url.includes('metadata-profiles')){if(failedProfiles){res.writeHead(503);res.end('{}');}else res.end(JSON.stringify([{id:'fixture-profile',revision:2,requiredFields:['processingTools'],definition:{name:'Perfil original',description:'Descripción original del perfil',language:'es',licenseId:'CC-BY-4.0'}}]));}
  else if(req.url.includes('privacy-policy'))res.end(JSON.stringify({required:true}));else res.end('{}');return;
 }
 const name=req.url.split('?')[0].slice(1);if(!/^[\w.-]+$/.test(name)||!fs.existsSync(path.join(root,name))){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path.join(root,name)));
});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await puppeteer.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.evaluateOnNewDocument(()=>{localStorage.setItem('base-repo-token','fixture');localStorage.setItem('base-repo-user',JSON.stringify({username:'fixture',role:'USER'}));});await page.setViewport({width:320,height:900});await page.goto(`http://127.0.0.1:${server.address().port}/create.html`);await page.waitForSelector('#dataset-profile-select option[value=fixture-profile]');await page.type('[name=title]','Título original <sin traducir>');await page.$eval('.creator-given',n=>{n.value='Autor original';n.dispatchEvent(new Event('input',{bubbles:true}));});await page.select('#dataset-profile-select','fixture-profile');await page.click('#apply-dataset-profile');await page.waitForSelector('#dataset-profile-confirm[open]');const beforeLanguage=requests;await page.select('[data-ui-locale]','en');assert.equal(await page.$eval('#dataset-profile-confirm-title',n=>n.textContent),'Apply metadata profile');assert.match(await page.$eval('#dataset-profile-confirm',n=>n.textContent),/Perfil original/);assert.match(await page.$eval('#dataset-profile-confirm',n=>n.textContent),/Tools and versions/);await page.click('#dataset-profile-confirm .primary');assert.equal(await page.$eval('[name=title]',n=>n.value),'Título original <sin traducir>');assert.equal(await page.$eval('.creator-given',n=>n.value),'Autor original');await page.$eval('[name=processingTools]',n=>{n.value='Herramienta original';n.dispatchEvent(new Event('input',{bubbles:true}));});
 await page.evaluate(()=>{const f=document.querySelector('#wizard-form');for(const [k,v]of Object.entries({institution:'Institución original',methodology:'Método original',licenseId:'CC-BY-4.0',privacyClassification:'NONE',publisher:'Editorial original'})){f.elements.namedItem(k).value=v;}f.elements.namedItem('privacyClassification').dispatchEvent(new Event('change'));const md=new DataTransfer();md.items.add(new File(['# Descripción original\nTexto original con data-i18n="login.title"'],'description.md',{type:'text/markdown'}));document.querySelector('#description-file').files=md.files;const files=new DataTransfer();files.items.add(new File(['x,y\n1,2'],'original.csv',{type:'text/csv'}));document.querySelector('#dataset-files').files=files.files;document.querySelector('#dataset-files').dispatchEvent(new Event('change'));});
 await page.$eval('#add-funding',n=>n.click());await page.$eval('[name=funding-funderName]',n=>{n.value='Financiador original';n.dispatchEvent(new Event('input',{bubbles:true}));});await page.$eval('#metadata-translations button',n=>n.click());await page.$eval('.translation-row input',n=>{n.value='en';n.dispatchEvent(new Event('input',{bubbles:true}));});await page.$eval('.translation-row label:nth-of-type(2) input',n=>{n.value='Author supplied English title';n.dispatchEvent(new Event('input',{bubbles:true}));});
 // Step transitions remain real UI actions; no writes before final confirmation.
 for(let step=0;step<7;step++){await page.click('#wizard-next');await page.waitForFunction(s=>!document.querySelector(`.wizard-panel[data-step="${s}"]`).hidden,{},step+1);}
 await page.waitForFunction(()=>!document.querySelector('#wizard-next').disabled);assert.match(await page.$eval('#preview-content',n=>n.textContent),/Citation preview \(draft\)/);assert.match(await page.$eval('#preview-content',n=>n.textContent),/Descripción original/);assert.match(await page.$eval('#preview-content',n=>n.textContent),/Método original/);await page.select('[data-ui-locale]','es');await page.waitForFunction(()=>document.querySelector('#preview-content').textContent.includes('Vista previa de cita'));assert.equal(await page.$eval('[name=title]',n=>n.value),'Título original <sin traducir>');await page.select('[data-ui-locale]','en');await page.waitForFunction(()=>document.querySelector('#preview-content').textContent.includes('Citation preview'));await page.click('#wizard-next');await page.click('#save-submit');assert.match(await page.$eval('#wizard-message',n=>n.textContent),/Confirm that you reviewed/);assert.equal(writes,0);assert.equal(requests,beforeLanguage);
 await page.evaluate(()=>{window.transferProbe=transfers.upload('/fixture-upload',new File(['abc'],'Nombre original <archivo>.csv')).then(()=>true);});await page.waitForFunction(()=>document.querySelector('.transfer-list').textContent.includes('waiting for server confirmation'));await page.select('[data-ui-locale]','es');assert.match(await page.$eval('.transfer-list',n=>n.textContent),/esperando confirmación/);await page.select('[data-ui-locale]','en');await page.evaluate(()=>window.transferProbe);assert.equal(transferRequests,1);assert.match(await page.$eval('.transfer-list',n=>n.textContent),/Upload completed/);assert.match(await page.$eval('.transfer-list',n=>n.textContent),/Nombre original <archivo>/);
 await page.addScriptTag({content:axe.source});const audit=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}));assert.deepEqual(audit.violations.map(v=>v.id),[],JSON.stringify(audit.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 // A failed profile load must stay a failure when switching language.
 failedProfiles=true;const second=await browser.newPage();await second.evaluateOnNewDocument(()=>{localStorage.setItem('base-repo-token','fixture');localStorage.setItem('base-repo-user',JSON.stringify({username:'fixture2',role:'USER'}));});await second.goto(`http://127.0.0.1:${server.address().port}/create.html`);await second.waitForFunction(()=>document.querySelector('#dataset-profile-status').textContent.includes('could not be loaded'));await second.select('[data-ui-locale]','es');assert.match(await second.$eval('#dataset-profile-status',n=>n.textContent),/No se pudieron consultar perfiles/);console.log('Wizard es/en 9 steps, profile state, author metadata/Markdown/forms preserved, no API calls/writes on locale change, English 320px axe: PASS');
 }finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
