#!/usr/bin/env bash
set -euo pipefail

# Never connects to a live database. All SQL runs in a throwaway local cluster.
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
MIGRATION="$ROOT/docs/migrations/2026-09-scientific-records.sql"
SOURCE_DUMP=""
SOURCE_FILES=""

usage() {
  cat <<'EOF'
Uso: tools/migrations/rehearse.sh [--db-dump respaldo.dump] [--files directorio]

Sin argumentos crea una base y archivos ficticios. Para ensayar una copia de
staging, use un pg_dump en formato custom (-Fc) y el directorio de datos
correspondiente. Nunca se conecta a la base de origen ni modifica --files.
EOF
}
while (($#)); do
  case "$1" in
    --db-dump) (($# >= 2)) || { usage >&2; exit 2; }; SOURCE_DUMP="$2"; shift 2 ;;
    --files) (($# >= 2)) || { usage >&2; exit 2; }; SOURCE_FILES="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) usage >&2; exit 2 ;;
  esac
done
[[ $EUID -ne 0 ]] || { echo 'Ejecute sin sudo: initdb no acepta root.' >&2; exit 2; }
[[ -z "$SOURCE_DUMP" || -r "$SOURCE_DUMP" ]] || { echo 'No se puede leer el dump.' >&2; exit 2; }
[[ -z "$SOURCE_FILES" || -d "$SOURCE_FILES" ]] || { echo 'No se encuentra el directorio de archivos.' >&2; exit 2; }
[[ -f "$MIGRATION" ]] || { echo 'No se encuentra la migración SQL.' >&2; exit 2; }

if command -v initdb >/dev/null 2>&1; then
  PG_BIN="$(dirname "$(command -v initdb)")"
else
  PG_BIN="$(dirname "$(find /usr/lib/postgresql -path '*/bin/initdb' -print | sort -V | tail -1)")"
fi
for command in initdb pg_ctl createdb dropdb psql pg_dump pg_restore; do
  [[ -x "$PG_BIN/$command" ]] || { echo "Falta PostgreSQL: $command" >&2; exit 2; }
done

umask 077
TEMP="$(mktemp -d /tmp/reduniv-migration.XXXXXXXX)"
mkdir -m 700 "$TEMP/socket" "$TEMP/files-original" "$TEMP/files-working" "$TEMP/files-backup"
started=false
cleanup() {
  if [[ "$started" == true ]]; then "$PG_BIN/pg_ctl" -D "$TEMP/pgdata" -m immediate stop >/dev/null 2>&1 || true; fi
  rm -rf -- "$TEMP"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

"$PG_BIN/initdb" -D "$TEMP/pgdata" -A trust --no-instructions > "$TEMP/initdb.log"
"$PG_BIN/pg_ctl" -D "$TEMP/pgdata" -l "$TEMP/postgres.log" \
  -o "-c listen_addresses='' -c unix_socket_directories='$TEMP/socket' -p 5432" start > "$TEMP/pgctl.log"
started=true
export PGHOST="$TEMP/socket" PGPORT=5432 PGUSER="$(id -un)" PGDATABASE=postgres
export PGOPTIONS='-c client_min_messages=warning'
"$PG_BIN/createdb" reduniv_rehearsal

if [[ -n "$SOURCE_DUMP" ]]; then
  "$PG_BIN/pg_restore" --no-owner --no-acl --exit-on-error -d reduniv_rehearsal "$SOURCE_DUMP" > "$TEMP/restore-source.log"
else
  "$PG_BIN/psql" -X -v ON_ERROR_STOP=1 -d reduniv_rehearsal <<'SQL' > "$TEMP/fixture.log"
CREATE TABLE repo_users (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         username varchar(80) NOT NULL, email varchar(255) NOT NULL);
INSERT INTO repo_users(username, email) VALUES ('rehearsal', 'rehearsal@example.invalid');
SQL
fi

dump_args=(--no-owner --no-acl)
if "$PG_BIN/pg_dump" --help | grep -q -- '--restrict-key'; then dump_args+=(--restrict-key=redunivrehearsal); fi
"$PG_BIN/psql" -X -v ON_ERROR_STOP=1 -d reduniv_rehearsal -f "$MIGRATION" > "$TEMP/migration-first.log"
"$PG_BIN/pg_dump" "${dump_args[@]}" --schema-only -d reduniv_rehearsal > "$TEMP/schema-first.sql"
"$PG_BIN/psql" -X -v ON_ERROR_STOP=1 -d reduniv_rehearsal -f "$MIGRATION" > "$TEMP/migration-second.log"
"$PG_BIN/pg_dump" "${dump_args[@]}" --schema-only -d reduniv_rehearsal > "$TEMP/schema-second.sql"
cmp -s "$TEMP/schema-first.sql" "$TEMP/schema-second.sql" || { echo 'La migración no es idempotente.' >&2; exit 1; }

if [[ -z "$SOURCE_DUMP" ]]; then
  "$PG_BIN/psql" -X -v ON_ERROR_STOP=1 -d reduniv_rehearsal <<'SQL' > "$TEMP/data-fixture.log"
INSERT INTO scientific_records(resource_id, status, version_label)
VALUES ('fixture-dataset', 'DRAFT', '1');
INSERT INTO fixity_audit_runs(id, status, started_at, checked)
VALUES ('00000000-0000-0000-0000-000000000001', 'COMPLETED', now(), 2);
SQL
fi

"$PG_BIN/pg_dump" "${dump_args[@]}" --data-only -d reduniv_rehearsal > "$TEMP/data-before.sql"
"$PG_BIN/pg_dump" "${dump_args[@]}" --schema-only -d reduniv_rehearsal > "$TEMP/schema-before.sql"
"$PG_BIN/pg_dump" -Fc --no-owner --no-acl -d reduniv_rehearsal -f "$TEMP/backup.dump"
"$PG_BIN/dropdb" reduniv_rehearsal
"$PG_BIN/createdb" reduniv_rehearsal
"$PG_BIN/pg_restore" --no-owner --no-acl --exit-on-error -d reduniv_rehearsal "$TEMP/backup.dump" > "$TEMP/restore-rehearsal.log"
"$PG_BIN/pg_dump" "${dump_args[@]}" --data-only -d reduniv_rehearsal > "$TEMP/data-after.sql"
"$PG_BIN/pg_dump" "${dump_args[@]}" --schema-only -d reduniv_rehearsal > "$TEMP/schema-after.sql"
cmp -s "$TEMP/schema-before.sql" "$TEMP/schema-after.sql" || { echo 'El esquema cambió después de restaurar.' >&2; exit 1; }
cmp -s "$TEMP/data-before.sql" "$TEMP/data-after.sql" || { echo 'Los datos cambiaron después de restaurar.' >&2; exit 1; }

if [[ -n "$SOURCE_FILES" ]]; then
  if [[ -n "$(find "$SOURCE_FILES" -type l -print -quit)" ]]; then
    echo 'La copia de archivos contiene enlaces simbólicos; respalde sus destinos antes del ensayo.' >&2
    exit 1
  fi
  cp -a -- "$SOURCE_FILES/." "$TEMP/files-original/"
else
  printf '# Descripción de prueba\n' > "$TEMP/files-original/description.md"
  printf 'columna\nvalor\n' > "$TEMP/files-original/datos.csv"
fi
cp -a -- "$TEMP/files-original/." "$TEMP/files-working/"
cp -a -- "$TEMP/files-working/." "$TEMP/files-backup/"
rm -rf -- "$TEMP/files-working"
mkdir -m 700 "$TEMP/files-working"
cp -a -- "$TEMP/files-backup/." "$TEMP/files-working/"
diff -qr -- "$TEMP/files-original" "$TEMP/files-working" >/dev/null || { echo 'Los archivos cambiaron después de restaurar.' >&2; exit 1; }

echo 'Migración idempotente y restauración de base/archivos verificadas en un clúster local efímero.'
if [[ -z "$SOURCE_DUMP" || -z "$SOURCE_FILES" ]]; then
  echo 'AVISO: faltó una copia real de staging; el ensayo no autoriza despliegue en producción.'
fi
