#!/usr/bin/env bash
set -euo pipefail

# Never connects to a live database. All SQL runs in a throwaway local cluster.
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
MIGRATION="$ROOT/docs/migrations/2026-09-scientific-records.sql"
SOURCE_DUMP=""
SOURCE_FILES=""
DIAGNOSTICS=""

usage() {
  cat <<'EOF'
Uso: tools/migrations/rehearse.sh [--db-dump respaldo.dump] [--files directorio]
                                [--diagnostics directorio-nuevo-privado]

Sin argumentos crea una base y archivos ficticios. Para ensayar una copia de
staging, use un pg_dump en formato custom (-Fc) y el directorio de datos
correspondiente. Nunca se conecta a la base de origen ni modifica --files.
EOF
}
while (($#)); do
  case "$1" in
    --db-dump) (($# >= 2)) || { usage >&2; exit 2; }; SOURCE_DUMP="$2"; shift 2 ;;
    --files) (($# >= 2)) || { usage >&2; exit 2; }; SOURCE_FILES="$2"; shift 2 ;;
    --diagnostics) (($# >= 2)) || { usage >&2; exit 2; }; DIAGNOSTICS="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) usage >&2; exit 2 ;;
  esac
done
[[ $EUID -ne 0 ]] || { echo 'Ejecute sin sudo: initdb no acepta root.' >&2; exit 2; }
[[ -z "$SOURCE_DUMP" || -r "$SOURCE_DUMP" ]] || { echo 'No se puede leer el dump.' >&2; exit 2; }
[[ -z "$SOURCE_FILES" || -d "$SOURCE_FILES" ]] || { echo 'No se encuentra el directorio de archivos.' >&2; exit 2; }
[[ -f "$MIGRATION" ]] || { echo 'No se encuentra la migración SQL.' >&2; exit 2; }

if command -v initdb >/dev/null 2>&1; then
  PG_BIN="$(dirname "$(command -v initdb)")"
else
  PG_BIN="$(dirname "$(find /usr/lib/postgresql -path '*/bin/initdb' -print | sort -V | tail -1)")"
fi
for command in initdb pg_ctl createdb dropdb psql pg_dump pg_restore; do
  [[ -x "$PG_BIN/$command" ]] || { echo "Falta PostgreSQL: $command" >&2; exit 2; }
done

umask 077
if [[ -n "$DIAGNOSTICS" ]]; then
  mkdir -m 700 -- "$DIAGNOSTICS" || { echo 'Use un directorio nuevo para diagnósticos privados.' >&2; exit 2; }
  DIAGNOSTICS="$(cd "$DIAGNOSTICS" && pwd)"
fi
# Preserve SQL exactly except pg_dump's random psql restriction token.
normalize_dump() {
  sed -E 's/^(\\(un)?restrict)[[:space:]]+[A-Za-z0-9]+$/\1 REDUNIV_COMPARISON_KEY/'
}
dump_for_comparison() {
  "$PG_BIN/pg_dump" "${dump_args[@]}" "$@" | normalize_dump
}
compare_dump() {
  local first=$1 second=$2 message=$3
  if cmp -s "$first" "$second"; then return 0; fi
  echo "$message" >&2
  if [[ -n "$DIAGNOSTICS" ]]; then
    cp -- "$first" "$second" "$DIAGNOSTICS/"
    diff -u -- "$first" "$second" > "$DIAGNOSTICS/difference.diff" || true
    cp -- "$TEMP"/*.log "$DIAGNOSTICS/"
    echo "Diagnóstico privado: $DIAGNOSTICS (puede contener datos sensibles; no publicar)." >&2
  fi
  return 1
}
TEMP="$(mktemp -d /tmp/reduniv-migration.XXXXXXXX)"
mkdir -m 700 "$TEMP/socket" "$TEMP/files-original" "$TEMP/files-working" "$TEMP/files-backup"
started=false
cleanup() {
  if [[ "$started" == true ]]; then "$PG_BIN/pg_ctl" -D "$TEMP/pgdata" -m immediate stop >/dev/null 2>&1 || true; fi
  rm -rf -- "$TEMP"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

"$PG_BIN/initdb" -D "$TEMP/pgdata" -A trust --no-instructions > "$TEMP/initdb.log"
"$PG_BIN/pg_ctl" -D "$TEMP/pgdata" -l "$TEMP/postgres.log" \
  -o "-c listen_addresses='' -c unix_socket_directories='$TEMP/socket' -p 5432" start > "$TEMP/pgctl.log"
started=true
export PGHOST="$TEMP/socket" PGPORT=5432 PGUSER="$(id -un)" PGDATABASE=postgres
export PGOPTIONS='-c client_min_messages=warning'
"$PG_BIN/createdb" reduniv_rehearsal

if [[ -n "$SOURCE_DUMP" ]]; then
  "$PG_BIN/pg_restore" --no-owner --no-acl --exit-on-error -d reduniv_rehearsal "$SOURCE_DUMP" > "$TEMP/restore-source.log"
else
  "$PG_BIN/psql" -X -v ON_ERROR_STOP=1 -d reduniv_rehearsal <<'SQL' > "$TEMP/fixture.log"
CREATE TABLE repo_users (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         username varchar(80) NOT NULL, email varchar(255) NOT NULL);
INSERT INTO repo_users(username, email) VALUES ('rehearsal', 'rehearsal@example.invalid');
-- Exercise upgrade from the legacy CHAR column, retaining an existing state.
CREATE TABLE orcid_oauth_states (
 state_hash char(64) PRIMARY KEY, resource_id varchar(255) NOT NULL,
 creator_id bigint NOT NULL, username varchar(80) NOT NULL,
 expires_at timestamptz NOT NULL, consumed_at timestamptz
);
INSERT INTO orcid_oauth_states(state_hash,resource_id,creator_id,username,expires_at)
VALUES (repeat('a',64),'legacy-resource',1,'rehearsal',now());
SQL
fi

dump_args=(--no-owner --no-acl)
DUMP_HELP="$("$PG_BIN/pg_dump" --help)"
if grep -q -- '--restrict-key' <<< "$DUMP_HELP"; then dump_args+=(--restrict-key=redunivrehearsal); fi
"$PG_BIN/psql" -X -v ON_ERROR_STOP=1 -d reduniv_rehearsal -f "$MIGRATION" > "$TEMP/migration-first.log"
"$PG_BIN/psql" -X -v ON_ERROR_STOP=1 -d reduniv_rehearsal <<'SQL' > "$TEMP/type-validation.log"
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_schema='public' AND table_name='orcid_oauth_states'
                  AND column_name='state_hash' AND data_type='character varying'
                  AND character_maximum_length=64) THEN
   RAISE EXCEPTION 'ORCID state hash must be VARCHAR(64) to match JPA';
 END IF;
END $$;
SQL
if [[ -z "$SOURCE_DUMP" ]]; then
  [[ "$("$PG_BIN/psql" -X -At -d reduniv_rehearsal -c "SELECT count(*) FROM orcid_oauth_states WHERE state_hash=repeat('a',64) AND resource_id='legacy-resource'")" == 1 ]] || { echo 'Se perdió el estado OAuth de prueba.' >&2; exit 1; }
fi
dump_for_comparison --schema-only -d reduniv_rehearsal > "$TEMP/schema-first.sql"
"$PG_BIN/psql" -X -v ON_ERROR_STOP=1 -d reduniv_rehearsal -f "$MIGRATION" > "$TEMP/migration-second.log"
dump_for_comparison --schema-only -d reduniv_rehearsal > "$TEMP/schema-second.sql"
compare_dump "$TEMP/schema-first.sql" "$TEMP/schema-second.sql" 'La migración no es idempotente.'

if [[ -z "$SOURCE_DUMP" ]]; then
  "$PG_BIN/psql" -X -v ON_ERROR_STOP=1 -d reduniv_rehearsal <<'SQL' > "$TEMP/data-fixture.log"
INSERT INTO scientific_records(resource_id, status, version_label)
VALUES ('fixture-dataset', 'DRAFT', '1');
INSERT INTO fixity_audit_runs(id, status, started_at, checked)
VALUES ('00000000-0000-0000-0000-000000000001', 'COMPLETED', now(), 2);
SQL
fi

dump_for_comparison --data-only -d reduniv_rehearsal > "$TEMP/data-before.sql"
dump_for_comparison --schema-only -d reduniv_rehearsal > "$TEMP/schema-before.sql"
"$PG_BIN/pg_dump" -Fc --no-owner --no-acl -d reduniv_rehearsal -f "$TEMP/backup.dump"
"$PG_BIN/dropdb" reduniv_rehearsal
"$PG_BIN/createdb" reduniv_rehearsal
"$PG_BIN/pg_restore" --no-owner --no-acl --exit-on-error -d reduniv_rehearsal "$TEMP/backup.dump" > "$TEMP/restore-rehearsal.log"
dump_for_comparison --data-only -d reduniv_rehearsal > "$TEMP/data-after.sql"
dump_for_comparison --schema-only -d reduniv_rehearsal > "$TEMP/schema-after.sql"
compare_dump "$TEMP/schema-before.sql" "$TEMP/schema-after.sql" 'El esquema cambió después de restaurar.'
compare_dump "$TEMP/data-before.sql" "$TEMP/data-after.sql" 'Los datos cambiaron después de restaurar.'

if [[ -n "$SOURCE_FILES" ]]; then
  if [[ -n "$(find "$SOURCE_FILES" -type l -print -quit)" ]]; then
    echo 'La copia de archivos contiene enlaces simbólicos; respalde sus destinos antes del ensayo.' >&2
    exit 1
  fi
  cp -a -- "$SOURCE_FILES/." "$TEMP/files-original/"
else
  printf '# Descripción de prueba\n' > "$TEMP/files-original/description.md"
  printf 'columna\nvalor\n' > "$TEMP/files-original/datos.csv"
fi
cp -a -- "$TEMP/files-original/." "$TEMP/files-working/"
cp -a -- "$TEMP/files-working/." "$TEMP/files-backup/"
rm -rf -- "$TEMP/files-working"
mkdir -m 700 "$TEMP/files-working"
cp -a -- "$TEMP/files-backup/." "$TEMP/files-working/"
diff -qr -- "$TEMP/files-original" "$TEMP/files-working" >/dev/null || { echo 'Los archivos cambiaron después de restaurar.' >&2; exit 1; }

echo 'Migración idempotente y restauración de base/archivos verificadas en un clúster local efímero.'
if [[ -z "$SOURCE_DUMP" || -z "$SOURCE_FILES" ]]; then
  echo 'AVISO: faltó una copia real de staging; el ensayo no autoriza despliegue en producción.'
fi
